import type { BossConfig, Level, UpgradeOption, Weapon, WeaponId } from './types';

/** Selectable final bosses. Cards are shuffled before every choice. */
export const BOSSES: BossConfig[] = [
  {
    id: 'flower',
    glyph: '🌻',
    name: { zh: '食人花', en: 'MAN-EATER BLOOM' },
    tag: { zh: '弹幕 · 召唤', en: 'BARRAGE · SUMMON' },
    description: {
      zh: '扎根不动的巨型食人花。扇形吐出种子弹幕，重伤后召唤藤蔓小怪并释放尖刺环。',
      en: 'A rooted giant bloom. Fans out seed barrages; when hurt it sprouts vines and thorn rings.',
    },
    color: 0xd977a4,
    hp: 1150,
    stationary: true,
  },
  {
    id: 'zombie',
    glyph: '🧟',
    name: { zh: '僵尸之王', en: 'PLAGUE SOVEREIGN' },
    tag: { zh: '召唤 · 压制', en: 'SUMMON · SWARM' },
    description: {
      zh: '缓慢逼近的腐烂君王，不断唤起僵尸潮。半血后狂暴加速并吐出腐毒扇面。',
      en: 'A rotting sovereign that shambles forward and raises zombie tides. Enrages below half health.',
    },
    color: 0x8fae72,
    hp: 1350,
  },
  {
    id: 'doll',
    glyph: '🪆',
    name: { zh: '洋娃娃', en: 'PORCELAIN DOLL' },
    tag: { zh: '机动 · 诡变', en: 'MOBILITY · TRICKERY' },
    description: {
      zh: '会瞬移的瓷器娃娃，从不可思议的角度射出缝衣针。半血后针雨翻倍。',
      en: 'A teleporting porcelain doll firing needles from impossible angles. Doubles the storm below half health.',
    },
    color: 0xd8b6c4,
    hp: 1050,
  },
  {
    id: 'scorpion',
    glyph: '🦂',
    name: { zh: '机械巨蝎', en: 'ARC SCORPION' },
    tag: { zh: '冲锋 · 横扫', en: 'CHARGE · SWEEP' },
    description: {
      zh: '合金甲壳的巨蝎：尾针锁定后全速冲撞，重伤后钻地突袭并甩出毒刺环。',
      en: 'An alloy-armored scorpion that locks on and charges; wounded, it burrows and flings venom rings.',
    },
    color: 0xa8b4c4,
    hp: 1250,
  },
  {
    id: 'crow',
    glyph: '🐦',
    name: { zh: '乌鸦稻草人', en: 'CROW SCARECROW' },
    tag: { zh: '空袭 · 场控', en: 'AIR RAID · ZONE' },
    description: {
      zh: '麦田里的守望者放出一群群乌鸦，凝视前方洒下恐惧弹幕。半血后乌鸦不歇。',
      en: 'The watcher of the fields sends crow flocks and dread barrages. The flock never rests below half health.',
    },
    color: 0x9a8fb8,
    hp: 1200,
  },
];

export const WORLD = { width: 1280, height: 800, inset: 62 };
export const WEAPONS: Record<WeaponId, Weapon> = {
  rifle: {
    id: 'rifle',
    name: { zh: '游骑兵', en: 'RANGER' },
    label: { zh: 'MK.01 / 突击步枪', en: 'MK.01 / ASSAULT RIFLE' },
    description: { zh: '稳定连射 · 中距离压制', en: 'STEADY AUTO FIRE · MID-RANGE CONTROL' },
    color: 0xf9bd7e,
    damage: 21,
    interval: 0.13,
    pellets: 1,
    spread: 0.035,
    speed: 920,
    magazine: 30,
    reload: 1.15,
    range: 760,
  },
  flamer: {
    id: 'flamer',
    name: { zh: '焚化者', en: 'INCINERATOR' },
    label: { zh: 'FL.02 / 喷火枪', en: 'FL.02 / FLAMETHROWER' },
    description: { zh: '锥形火焰 · 贴脸洗怪', en: 'CONE OF FIRE · POINT-BLANK PURGE' },
    color: 0xff8a5c,
    damage: 7,
    interval: 0.05,
    pellets: 1,
    spread: 0.3,
    speed: 620,
    magazine: 100,
    reload: 1.6,
    range: 230,
  },
};
export const UPGRADES: UpgradeOption[] = [
  { id: 'shots', label: { zh: '弹丸 +1', en: '+1 PROJECTILE' } },
  { id: 'damage', label: { zh: '伤害 +20%', en: '+20% DAMAGE' } },
  { id: 'rate', label: { zh: '射速 +15%', en: '+15% FIRE RATE' } },
  { id: 'pierce', label: { zh: '穿透 +1', en: '+1 PIERCE' } },
  { id: 'mag', label: { zh: '弹匣 +50%', en: '+50% MAGAZINE' } },
];
export const LEVELS: Level[] = [
  {
    name: { zh: '低语草野', en: 'THE WHISPERING MEADOW' },
    code: 'THE WHISPERING MEADOW',
    subtitle: {
      zh: '蛛群在草丛深处结网，清出一条路',
      en: 'The webs run deep in the grass. Cut a path through',
    },
    accent: 0x9fd08c,
    floor: 0x2e4626,
    theme: 'grass',
    obstacles: [
      { x: 287, y: 232, w: 132, h: 66 },
      { x: 856, y: 484, w: 136, h: 68 },
      { x: 324, y: 510, w: 76, h: 94 },
      { x: 882, y: 212, w: 74, h: 92 },
    ],
    barrels: [
      { x: 450, y: 245 },
      { x: 825, y: 553 },
      { x: 945, y: 397 },
    ],
    hpScale: 1,
    waves: [
      ['crawler', 'crawler', 'crawler', 'spitter', 'crawler', 'crawler', 'spitter'],
      ['crawler', 'spitter', 'crawler', 'brute', 'crawler', 'spitter', 'crawler', 'crawler'],
    ],
  },
  {
    name: { zh: '巨木树洞', en: 'THE HOLLOW GIANT' },
    code: 'THE HOLLOW GIANT',
    subtitle: {
      zh: '蝠群在年轮间盘旋，别被音波钉在原地',
      en: 'Bats swarm between the rings. Do not get pinned by their cries',
    },
    accent: 0xd8a86b,
    floor: 0x3d2c1c,
    theme: 'hollow',
    obstacles: [
      { x: 355, y: 175, w: 85, h: 140 },
      { x: 355, y: 492, w: 85, h: 135 },
      { x: 845, y: 175, w: 85, h: 140 },
      { x: 845, y: 492, w: 85, h: 135 },
      { x: 580, y: 352, w: 125, h: 60 },
    ],
    barrels: [
      { x: 485, y: 242 },
      { x: 793, y: 561 },
      { x: 753, y: 347 },
    ],
    hpScale: 2,
    waves: [
      [
        'crawler',
        'spitter',
        'spitter',
        'crawler',
        'crawler',
        'spitter',
        'crawler',
        'crawler',
        'spitter',
        'crawler',
        'crawler',
        'spitter',
        'crawler',
      ],
      [
        'brute',
        'brute',
        'brute',
        'spitter',
        'spitter',
        'spitter',
        'spitter',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
      ],
    ],
  },
  {
    name: { zh: '月面前哨', en: 'LUNAR OUTPOST' },
    code: 'LUNAR OUTPOST',
    subtitle: {
      zh: '低重力区的异形巢穴，掩体后就是真空',
      en: 'An alien nest under low gravity. Cover is all that keeps you breathing',
    },
    accent: 0x8fb6e8,
    floor: 0x232c40,
    theme: 'moon',
    obstacles: [
      { x: 232, y: 205, w: 128, h: 62 },
      { x: 918, y: 205, w: 128, h: 62 },
      { x: 232, y: 545, w: 128, h: 62 },
      { x: 918, y: 545, w: 128, h: 62 },
      { x: 560, y: 190, w: 160, h: 56 },
      { x: 560, y: 590, w: 160, h: 56 },
    ],
    barrels: [
      { x: 398, y: 296 },
      { x: 884, y: 300 },
      { x: 745, y: 560 },
    ],
    hpScale: 4,
    waves: [
      [
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'spitter',
        'spitter',
        'spitter',
        'spitter',
        'brute',
        'brute',
      ],
      [
        'brute',
        'brute',
        'brute',
        'spitter',
        'spitter',
        'spitter',
        'spitter',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
      ],
    ],
  },
  {
    name: { zh: '万像角斗场', en: 'PANOPTES ARENA' },
    code: 'PANOPTES ARENA',
    subtitle: {
      zh: '全部猎手齐聚于此——选定你的宿敌',
      en: 'Every hunter gathers here. Choose your nemesis',
    },
    accent: 0xc49ae0,
    floor: 0x33233c,
    theme: 'arena',
    obstacles: [
      { x: 282, y: 248, w: 84, h: 95 },
      { x: 910, y: 248, w: 84, h: 95 },
      { x: 282, y: 500, w: 84, h: 70 },
      { x: 910, y: 500, w: 84, h: 70 },
    ],
    barrels: [
      { x: 413, y: 323 },
      { x: 858, y: 525 },
    ],
    hpScale: 8,
    waves: [
      [
        'crawler!',
        'crawler!',
        'crawler!',
        'crawler!',
        'crawler!',
        'crawler!',
        'spitter!',
        'spitter!',
        'brute!',
        'brute!',
      ],
      [
        'boss',
        'crawler',
        'crawler',
        'crawler',
        'crawler',
        'spitter',
        'spitter',
        'spitter',
        'spitter',
      ],
    ],
  },
];
