import type { BossConfig, Level, Skill, Weapon, WeaponId } from './types';

/** Selectable final bosses. Cards are shuffled before every choice. */
export const BOSSES: BossConfig[] = [
  {
    id: 'flower',
    glyph: '🌻',
    name: { zh: '食人花', en: 'MAN-EATER BLOOM' },
    tag: { zh: '弹幕 · 召唤', en: 'BARRAGE · SUMMON' },
    description: {
      zh: '扎根不动的巨型食人花。扇形吐出种子弹幕，重伤后召唤藤蔓小怪并释放尖刺环。',
      en: 'A rooted giant bloom. Fans out seed barrages; when hurt it sprouts vines and thorn rings.',
    },
    color: 0xd977a4,
    hp: 1150,
    stationary: true,
  },
  {
    id: 'zombie',
    glyph: '🧟',
    name: { zh: '僵尸之王', en: 'PLAGUE SOVEREIGN' },
    tag: { zh: '召唤 · 压制', en: 'SUMMON · SWARM' },
    description: {
      zh: '缓慢逼近的腐烂君王，不断唤起僵尸潮。半血后狂暴加速并吐出腐毒扇面。',
      en: 'A rotting sovereign that shambles forward and raises zombie tides. Enrages below half health.',
    },
    color: 0x8fae72,
    hp: 1350,
  },
  {
    id: 'doll',
    glyph: '🪆',
    name: { zh: '洋娃娃', en: 'PORCELAIN DOLL' },
    tag: { zh: '机动 · 诡变', en: 'MOBILITY · TRICKERY' },
    description: {
      zh: '会瞬移的瓷器娃娃，从不可思议的角度射出缝衣针。半血后针雨翻倍。',
      en: 'A teleporting porcelain doll firing needles from impossible angles. Doubles the storm below half health.',
    },
    color: 0xd8b6c4,
    hp: 1050,
  },
  {
    id: 'scorpion',
    glyph: '🦂',
    name: { zh: '机械巨蝎', en: 'ARC SCORPION' },
    tag: { zh: '冲锋 · 横扫', en: 'CHARGE · SWEEP' },
    description: {
      zh: '合金甲壳的巨蝎：尾针锁定后全速冲撞，重伤后钻地突袭并甩出毒刺环。',
      en: 'An alloy-armored scorpion that locks on and charges; wounded, it burrows and flings venom rings.',
    },
    color: 0xa8b4c4,
    hp: 1250,
  },
  {
    id: 'crow',
    glyph: '🐦',
    name: { zh: '乌鸦稻草人', en: 'CROW SCARECROW' },
    tag: { zh: '空袭 · 场控', en: 'AIR RAID · ZONE' },
    description: {
      zh: '麦田里的守望者放出一群群乌鸦，凝视前方洒下恐惧弹幕。半血后乌鸦不歇。',
      en: 'The watcher of the fields sends crow flocks and dread barrages. The flock never rests below half health.',
    },
    color: 0x9a8fb8,
    hp: 1200,
  },
];

export const WORLD = { width: 1280, height: 800, inset: 62 };
export const WEAPONS: Record<WeaponId, Weapon> = {
  rifle: {
    id: 'rifle',
    name: { zh: '游骑兵', en: 'RANGER' },
    label: { zh: 'MK.01 / 突击步枪', en: 'MK.01 / ASSAULT RIFLE' },
    description: { zh: '稳定连射 · 中距离压制', en: 'STEADY AUTO FIRE · MID-RANGE CONTROL' },
    color: 0xf9bd7e,
    damage: 21,
    interval: 0.13,
    pellets: 1,
    spread: 0.035,
    speed: 920,
    magazine: 30,
    reload: 1.15,
    range: 760,
  },
  shotgun: {
    id: 'shotgun',
    name: { zh: '破门者', en: 'BREACHER' },
    label: { zh: 'SG.08 / 霰弹枪', en: 'SG.08 / SHOTGUN' },
    description: { zh: '六发散射 · 近身爆发', en: 'SIX-PELLET SPREAD · CLOSE BURST' },
    color: 0xff946d,
    damage: 18,
    interval: 0.58,
    pellets: 6,
    spread: 0.3,
    speed: 770,
    magazine: 8,
    reload: 1.5,
    range: 410,
  },
  arc: {
    id: 'arc',
    name: { zh: '离子蜂', en: 'ION WASP' },
    label: { zh: 'EC.03 / 脉冲枪', en: 'EC.03 / PULSE CARBINE' },
    description: { zh: '高频脉冲 · 持续压制', en: 'RAPID PULSES · SUSTAINED PRESSURE' },
    color: 0xbaa1ff,
    damage: 13,
    interval: 0.072,
    pellets: 1,
    spread: 0.055,
    speed: 1050,
    magazine: 44,
    reload: 1.35,
    range: 850,
  },
};
export const SKILLS: Skill[] = [
  {
    id: 'chain',
    name: { zh: '连锁电弧', en: 'CHAIN ARC' },
    tag: { zh: '连锁 / 群体伤害', en: 'CHAIN / CROWD DAMAGE' },
    description: {
      zh: '每 3 次命中释放电弧，跳向附近 2 个敌人。霰弹命中也能触发。',
      en: 'Every third hit arcs to 2 nearby enemies. Shotgun pellets can trigger it.',
    },
    color: '#9ed6d7',
    icon: 'bolt',
  },
  {
    id: 'cryo',
    name: { zh: '霜冻弹芯', en: 'CRYO CORE' },
    tag: { zh: '控制 / 安全空间', en: 'CONTROL / SAFE SPACE' },
    description: {
      zh: '子弹使敌人减速 45%。拉开距离，让追击者变成活靶。',
      en: 'Shots slow enemies by 45%. Create distance and turn pursuers into targets.',
    },
    color: '#b5daef',
    icon: 'snow',
  },
  {
    id: 'pierce',
    name: { zh: '贯穿弹道', en: 'PIERCING TRAJECTORY' },
    tag: { zh: '穿透 / 火力效率', en: 'PIERCE / FIREPOWER EFFICIENCY' },
    description: {
      zh: '子弹额外穿透 2 个敌人，伤害提高 15%。在狭窄通道尤其有效。',
      en: 'Shots pierce 2 additional enemies and deal 15% more damage. Excels in corridors.',
    },
    color: '#d7bcf5',
    icon: 'arrow',
  },
  {
    id: 'nova',
    name: { zh: '闪避新星', en: 'DASH NOVA' },
    tag: { zh: '机动 / 爆发', en: 'MOBILITY / BURST' },
    description: {
      zh: '冲刺起点引发范围爆破，造成 65 点伤害。冲刺冷却缩短 25%。',
      en: 'Dashing detonates a 65-damage nova at the start and reduces dash cooldown by 25%.',
    },
    color: '#f6be91',
    icon: 'sun',
  },
  {
    id: 'leech',
    name: { zh: '战地修复', en: 'FIELD REPAIR' },
    tag: { zh: '续航 / 反击', en: 'SUSTAIN / COUNTERATTACK' },
    description: {
      zh: '每击败一个敌人恢复 3 点生命。生命低于一半时伤害提高 30%。',
      en: 'Restore 3 health per kill. Deal 30% more damage while below half health.',
    },
    color: '#b6ddae',
    icon: 'plus',
  },
  {
    id: 'haste',
    name: { zh: '过载机匣', en: 'OVERDRIVE MAG' },
    tag: { zh: '射速 / 节奏', en: 'FIRE RATE / TEMPO' },
    description: {
      zh: '射速提高 25%，换弹加快 30%。把持续火力变成你的优势。',
      en: 'Fire 25% faster and reload 30% faster. Turn sustained fire into an advantage.',
    },
    color: '#efce80',
    icon: 'fast',
  },
];
export const LEVELS: Level[] = [
  {
    name: { zh: '低语草野', en: 'THE WHISPERING MEADOW' },
    code: 'THE WHISPERING MEADOW',
    subtitle: {
      zh: '蛛群在草丛深处结网，清出一条路',
      en: 'The webs run deep in the grass. Cut a path through',
    },
    accent: 0x9fd08c,
    floor: 0x2e4626,
    theme: 'grass',
    obstacles: [
      { x: 287, y: 232, w: 132, h: 66 },
      { x: 856, y: 484, w: 136, h: 68 },
      { x: 324, y: 510, w: 76, h: 94 },
      { x: 882, y: 212, w: 74, h: 92 },
    ],
    barrels: [
      { x: 450, y: 245 },
      { x: 825, y: 553 },
      { x: 945, y: 397 },
    ],
    waves: [
      ['crawler', 'crawler', 'crawler', 'spitter', 'crawler', 'crawler', 'spitter'],
      ['crawler', 'spitter', 'crawler', 'brute', 'crawler', 'spitter', 'crawler', 'crawler'],
    ],
  },
  {
    name: { zh: '巨木树洞', en: 'THE HOLLOW GIANT' },
    code: 'THE HOLLOW GIANT',
    subtitle: {
      zh: '蝠群在年轮间盘旋，别被音波钉在原地',
      en: 'Bats swarm between the rings. Do not get pinned by their cries',
    },
    accent: 0xd8a86b,
    floor: 0x3d2c1c,
    theme: 'hollow',
    obstacles: [
      { x: 355, y: 175, w: 85, h: 140 },
      { x: 355, y: 492, w: 85, h: 135 },
      { x: 845, y: 175, w: 85, h: 140 },
      { x: 845, y: 492, w: 85, h: 135 },
      { x: 580, y: 352, w: 125, h: 60 },
    ],
    barrels: [
      { x: 485, y: 242 },
      { x: 793, y: 561 },
      { x: 753, y: 347 },
    ],
    waves: [
      ['crawler', 'spitter', 'spitter', 'crawler', 'crawler', 'spitter', 'crawler'],
      ['brute', 'spitter', 'crawler', 'brute', 'crawler', 'spitter', 'crawler', 'crawler'],
    ],
  },
  {
    name: { zh: '月面前哨', en: 'LUNAR OUTPOST' },
    code: 'LUNAR OUTPOST',
    subtitle: {
      zh: '低重力区的异形巢穴，掩体后就是真空',
      en: 'An alien nest under low gravity. Cover is all that keeps you breathing',
    },
    accent: 0x8fb6e8,
    floor: 0x232c40,
    theme: 'moon',
    obstacles: [
      { x: 232, y: 205, w: 128, h: 62 },
      { x: 918, y: 205, w: 128, h: 62 },
      { x: 232, y: 545, w: 128, h: 62 },
      { x: 918, y: 545, w: 128, h: 62 },
      { x: 560, y: 190, w: 160, h: 56 },
      { x: 560, y: 590, w: 160, h: 56 },
    ],
    barrels: [
      { x: 398, y: 296 },
      { x: 884, y: 300 },
      { x: 745, y: 560 },
    ],
    waves: [
      ['crawler', 'crawler', 'spitter', 'brute', 'crawler', 'spitter', 'crawler', 'crawler'],
      [
        'brute',
        'spitter',
        'crawler',
        'spitter',
        'crawler',
        'brute',
        'spitter',
        'crawler',
        'crawler',
      ],
    ],
  },
  {
    name: { zh: '万像角斗场', en: 'PANOPTES ARENA' },
    code: 'PANOPTES ARENA',
    subtitle: {
      zh: '全部猎手齐聚于此——选定你的宿敌',
      en: 'Every hunter gathers here. Choose your nemesis',
    },
    accent: 0xc49ae0,
    floor: 0x33233c,
    theme: 'arena',
    obstacles: [
      { x: 282, y: 248, w: 84, h: 95 },
      { x: 910, y: 248, w: 84, h: 95 },
      { x: 282, y: 500, w: 84, h: 70 },
      { x: 910, y: 500, w: 84, h: 70 },
    ],
    barrels: [
      { x: 413, y: 323 },
      { x: 858, y: 525 },
    ],
    waves: [
      ['crawler!', 'spitter!', 'brute!', 'crawler!', 'spitter!', 'crawler!'],
      ['boss', 'crawler', 'spitter', 'crawler'],
    ],
  },
];
