import type { Level, Skill, Weapon, WeaponId } from './types';

export const WORLD = { width: 1280, height: 800, inset: 62 };
export const WEAPONS: Record<WeaponId, Weapon> = {
  rifle: {
    id: 'rifle',
    name: '游骑兵',
    label: 'MK.01 / 突击步枪',
    description: '稳定连射 · 中距离压制',
    color: 0xf9bd7e,
    damage: 21,
    interval: 0.13,
    pellets: 1,
    spread: 0.035,
    speed: 920,
    magazine: 30,
    reload: 1.15,
    range: 760,
  },
  shotgun: {
    id: 'shotgun',
    name: '破门者',
    label: 'SG.08 / 霰弹枪',
    description: '六发散射 · 近身爆发',
    color: 0xff946d,
    damage: 18,
    interval: 0.58,
    pellets: 6,
    spread: 0.3,
    speed: 770,
    magazine: 8,
    reload: 1.5,
    range: 410,
  },
  arc: {
    id: 'arc',
    name: '离子蜂',
    label: 'EC.03 / 脉冲枪',
    description: '高频脉冲 · 持续压制',
    color: 0xbaa1ff,
    damage: 13,
    interval: 0.072,
    pellets: 1,
    spread: 0.055,
    speed: 1050,
    magazine: 44,
    reload: 1.35,
    range: 850,
  },
};
export const SKILLS: Skill[] = [
  {
    id: 'chain',
    name: '连锁电弧',
    tag: '连锁 / 群体伤害',
    description: '每 3 次命中释放电弧，跳向附近 2 个敌人。霰弹命中也能触发。',
    color: '#9ed6d7',
    icon: 'bolt',
  },
  {
    id: 'cryo',
    name: '霜冻弹芯',
    tag: '控制 / 安全空间',
    description: '子弹使敌人减速 45%。拉开距离，让追击者变成活靶。',
    color: '#b5daef',
    icon: 'snow',
  },
  {
    id: 'pierce',
    name: '贯穿弹道',
    tag: '穿透 / 火力效率',
    description: '子弹额外穿透 2 个敌人，伤害提高 15%。在狭窄通道尤其有效。',
    color: '#d7bcf5',
    icon: 'arrow',
  },
  {
    id: 'nova',
    name: '闪避新星',
    tag: '机动 / 爆发',
    description: '冲刺起点引发范围爆破，造成 65 点伤害。冲刺冷却缩短 25%。',
    color: '#f6be91',
    icon: 'sun',
  },
  {
    id: 'leech',
    name: '战地修复',
    tag: '续航 / 反击',
    description: '每击败一个敌人恢复 3 点生命。生命低于一半时伤害提高 30%。',
    color: '#b6ddae',
    icon: 'plus',
  },
  {
    id: 'haste',
    name: '过载机匣',
    tag: '射速 / 节奏',
    description: '射速提高 25%，换弹加快 30%。把持续火力变成你的优势。',
    color: '#efce80',
    icon: 'fast',
  },
];
export const LEVELS: Level[] = [
  {
    name: '孢子中庭',
    en: 'THE OVERGROWN ATRIUM',
    subtitle: '清除感染群，重新接通传送门',
    accent: 0x91c9ac,
    floor: 0x263936,
    obstacles: [
      { x: 287, y: 232, w: 132, h: 66 },
      { x: 856, y: 484, w: 136, h: 68 },
      { x: 324, y: 510, w: 76, h: 94 },
      { x: 882, y: 212, w: 74, h: 92 },
    ],
    barrels: [
      { x: 450, y: 245 },
      { x: 825, y: 553 },
      { x: 945, y: 397 },
    ],
    waves: [
      ['crawler', 'crawler', 'crawler', 'spitter', 'crawler', 'crawler', 'spitter'],
      ['crawler', 'spitter', 'crawler', 'brute', 'crawler', 'spitter', 'crawler', 'crawler'],
    ],
  },
  {
    name: '冷却回廊',
    en: 'THE COOLANT PASSAGE',
    subtitle: '利用掩体，突破重甲防线',
    accent: 0x94bfd1,
    floor: 0x26363e,
    obstacles: [
      { x: 355, y: 175, w: 85, h: 140 },
      { x: 355, y: 492, w: 85, h: 135 },
      { x: 845, y: 175, w: 85, h: 140 },
      { x: 845, y: 492, w: 85, h: 135 },
      { x: 580, y: 352, w: 125, h: 60 },
    ],
    barrels: [
      { x: 485, y: 242 },
      { x: 793, y: 561 },
      { x: 753, y: 347 },
    ],
    waves: [
      ['crawler', 'spitter', 'spitter', 'brute', 'crawler', 'crawler', 'spitter', 'crawler'],
      [
        'brute',
        'spitter',
        'crawler',
        'brute',
        'spitter',
        'crawler',
        'spitter',
        'crawler',
        'crawler',
      ],
    ],
  },
  {
    name: '反应堆之心',
    en: 'HEART OF THE REACTOR',
    subtitle: '击败孢核守卫，终止感染',
    accent: 0xda999b,
    floor: 0x3b3037,
    obstacles: [
      { x: 282, y: 248, w: 84, h: 95 },
      { x: 910, y: 248, w: 84, h: 95 },
      { x: 282, y: 500, w: 84, h: 70 },
      { x: 910, y: 500, w: 84, h: 70 },
    ],
    barrels: [
      { x: 413, y: 323 },
      { x: 858, y: 525 },
    ],
    waves: [
      ['brute', 'crawler', 'spitter', 'crawler', 'spitter', 'brute'],
      ['boss', 'crawler', 'crawler', 'spitter', 'crawler'],
    ],
  },
];
